[project]
name = "unnecessary-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.2",
    "matplotlib>=3.10.6",
    "moviepy>=2.2.1",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "pillow>=11.3.0",
]
